'use strict';

const payloads = {
    //All the payloads used inside Facebook Messenger json files
    FACEBOOK_CAB_OLA:'FACEBOOK_CAB_OLA',
    FACEBOOK_CAB_UBER: 'FACEBOOK_CAB_UBER',
    FACEBOOK_FLIPKART_CANCEL: 'PAYLOAD_FLIPKART_CANCEL',
    FACEBOOK_FLIPKART_SHOW_MORE: 'PAYLOAD_FLIPKART_SHOW_MORE',
    FACEBOOK_GET_STARTED: 'PAYLOAD_GET_STARTED',
    FACEBOOK_PERSISTENT_MENU_GET_UBER_CAB: 'PAYLOAD_PERSISTENT_MENU_GET_UBER_CAB',
    FACEBOOK_PERSISTENT_MENU_FLIPKART_OFFERS: 'PAYLOAD_PERSISTENT_MENU_FLIPKART_OFFERS',
    FACEBOOK_PERSISTENT_MENU_HELP: 'PAYLOAD_PERSISTENT_MENU_HELP'
}

module.exports = payloads;